format = """
$directory\
$git_branch\
$git_status\
$python\
$fill\
$cmd_duration\
$status $line_break\
$character"""

[directory]
style = "bold cyan"
truncation_length = 3
truncate_to_repo = true

[git_branch]
symbol = ""
style = "bold red"

[git_status]
style = "red"
format = '([$all_status$ahead_behind]($style) )'

[python]
format = "[($virtualenv)]($style) "
style = "yellow"

[docker_context]
symbol = "dkr "
style = "bold blue"
format = "[$symbol$context]($style) "
detect_files = ["Dockerfile", "docker-compose.yml"]

[podman]
symbol = "pod "
style = "bold magenta"
format = "[$symbol$name]($style) "
detect_files = ["Containerfile", "podman-compose.yml"]

[status]
disabled = false
format = '[$symbol]($style) '
symbol = "!"
style = "bold red"

[character]
success_symbol = "[>](green) "
error_symbol = "[>](red) "

[fill]
symbol = " "

[cmd_duration]
style = "dimmed white"
format = "[$duration]($style)"
