"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

[directory]
style = "#7FBBB3" # Everforest Blue

[character]
success_symbol = "[❯](#D699B6)" # Everforest Purple
error_symbol = "[❯](#E67E80)"   # Everforest Red
vimcmd_symbol = "[❮](#A7C080)"   # Everforest Green

[git_branch]
format = "[$branch]($style)"
style = "#859289" # Everforest Grey1

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "#83C092" # Everforest Aqua
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "#859289" # Everforest Grey1

[cmd_duration]
format = "[$duration]($style) "
style = "#DBBC7F" # Everforest Yellow

[python]
format = "[$virtualenv]($style) "
style = "#A7C080" # Everforest Green
detect_extensions = []
detect_files = []
