add_newline = true
command_timeout = 200

format = """
 $directory\
$git_branch\
$git_status
 $character"""

[character]
# Macchiato Red for error, Macchiato Green for success
success_symbol = "[❯](bold #a6da95)"
error_symbol = "[✗](bold #ed8796)"

[directory]
truncation_length = 2
truncation_symbol = "…/"
# Macchiato Sapphire for the root, Sky for the rest of the path
style = "bold #91d7e3"
repo_root_style = "bold #7dc4e4"
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "

[git_branch]
format = "on [$symbol$branch]($style) "
symbol = " "
# Macchiato Lavender
style = "italic #b7bdf8"

[git_status]
format = '[$all_status]($style)'
# Macchiato Teal for general status, but specific colors for urgency
style = "#8bd5ca"
ahead = "[⇡${count}](bold #eed49f) "      # Yellow
diverged = "[⇕⇡${ahead_count}⇣${behind_count}](bold #f5a97f) " # Peach
behind = "[⇣${count}](bold #eed49f) "     # Yellow
conflicted = "[ ](bold #ed8796)"         # Red
up_to_date = "[ ](bold #a6da95)"         # Green
untracked = "[? ](bold #c6a0f6)"          # Mauve
modified = "[ ](bold #f5a97f)"          # Peach
stashed = "[󰒑 ](bold #b7bdf8)"           # Lavender
staged = "[+ ](bold #a6da95)"             # Green
renamed = "[󰑕 ](bold #91d7e3)"           # Sky
deleted = "[󰗨 ](bold #ed8796)"           # Red
