general.import = [
  "~/.config/alacritty/themes/catppuccin-mocha.toml"
]

[terminal.shell]
program = "/bin/fish"

[window]
startup_mode = "Maximized"
decorations = "None"
padding = { x = 1, y = 1 }
opacity = 1

[font]
normal = { family = "IntoneMono Nerd Font", style = "Regular" }
bold = { family = "IntoneMono Nerd Font", style = "Bold" }
italic = { family = "IntoneMono Nerd Font", style = "Italic" }
bold_italic = { family = "IntoneMono Nerd Font", style = "Bold Italic" }
size = 12

[cursor]
style = { shape = "Beam", blinking = "Off" }
thickness = 0.3

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>\t"

[keyboard]
bindings = [
  { key = "Plus",  mods = "Control|Shift", action = "IncreaseFontSize" },
  { key = "Minus", mods = "Control|Shift", action = "DecreaseFontSize" },
  { key = "Key0",  mods = "Control|Shift", action = "ResetFontSize" }
]
